on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Tabelog URL'
        required: true
      type:
        description: 'Type of restaurant'
        required: true
        options:
          - 'SUSHI'
          - 'YAKINIKU'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          YAKINIKU_DATABASE_ID: ${{ secrets.YAKINIKU_DATABASE_ID }}
          SUSHI_DATABASE_ID: ${{ secrets.SUSHI_DATABASE_ID }}
        run: |
          node dist/app.js SUSHI https://tabelog.com/tokyo/A1301/A130101/13270948/ 
