on:
  repository_dispatch:
    types:
      - new
      - new_action_dispatcher
  workflow_dispatch:
    inputs:
      url:
        description: 'Tabelog URL'
        required: true
      type:
        description: 'Type of restaurant'
        required: true
        type: choice
        options:
          - 'SUSHI'
          - 'YAKINIKU'
          - 'OKONOMIYAKI'

jobs:
  run_in_workflow_dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          node dist/app.js ${{ github.event.inputs.type }} ${{ github.event.inputs.url }} 

  run_in_repository_dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' && ${{ github.event.client_payload.passed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          node dist/app.js ${{ github.event.client_payload.type }} ${{ github.event.client_payload.url }}

  run_in_repository_dispatch_dispatcher:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' && github.event.action == "new_action_dispatcher" && ${{ github.event.client_payload.passed }}
    steps:
      - name: Checkout
        run: |
          echo "Checkout"
